spring.application.name=techcup-backend
server.port=8080
# Para funcionamiento de swagger
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# JWT
jwt.secret=TechCup2025SecretKeyForJWTAuthenticationMinimum32Characters
jwt.expiration=86400000

# Logs SLF4J
logging.file.name=logs/techcup.log
logging.level.edu.dosw.techcup=INFO
logging.level.root=WARN