spring.application.name=techcup-backend
server.port=8080
# Para funcionamiento de swagger
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Logs SLF4J
logging.file.name=logs/techcup.log
logging.level.edu.dosw.techcup=INFO
logging.level.root=WARN